### ISSUE TITLE
full report 1.6

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#37]
-there is still creepers
-who is that grick? in deathouse
-bella after getting dog/cat egg to bella there will be no trigger follow up
-toad wont be trigger
-it's not a choise you can choose all 3 famillars
-church barrier block the father to talk to if it was 2 blocks lower it wont block willemina rikolova so we can talk to them
-travel to krezk not found(i saw the place between abby to valaki
-wizard of wines no idea what to do or where to get

-missing the tab vallaki but missions till tell the wife are there
-tab castle ravenloft is missing

**Comment by teagan75** [comment]
- I haven’t gotten rid of creepers yet
- the grick is just a monster
- I was certain I changed Bella but can you try copying her clone in?
- you can make all three yes but only one can be out at a time
- will see if placing the room down two blocks still reaches the altar power
- Krezk is by the abbey but that quest isn’t finished
- wizard of Wines isn’t even in the map yet lol
- I forgot to add the new quests for the book. I pushed another update. You will need to run the command /bq_admin default load once updated

**Comment by teagan75** [comment]
If you know how to use the npc wand, could you try something with Bella? Right click her with wand, go to global tab, dialogues, bonegrinder, Bella Sunbane, Availability options, Select Dialogue, change first Always to Before, click select dialogue, Bella II, then press Select at the bottom. Exit out and try it

**Comment by satanKami** [comment]
there is no bella clone in the server or in clones.
 ive done what you said from after to before 
but the dialog option is empty and the quest itself isn't attached to the dialog ive attached it and now that i talked to her i got the owl quest

edit:the quest owl familiar isnt connected to owl quest and once you buy the dog it wont go on

and yes I've learned  from the videos how to play with npc mod
p.s sorry i didn't replay i was asleep >_<

**Comment by satanKami** [comment]
full report 1.6.1
- the tiger is too big and cant get out to attack me(also can i tame him?)-and the quest didn't say kill it
- there is no location block in krezk but there is a hole near the fountion`
- the quest book wont say if you choose van you wont be able to talk to wisteria
- bella still not fixed
- didnt got the invention from stand(spying eyes)`
- other places like werewolf den is unable due to "new quest"

**Comment by teagan75** [comment]
- stupid tiger lol. He got out with my testing but I will try again. 
- Krezk isn’t ready yet
- Wisteria is open for everyone after Offailia quests
- did you talk to Ernst?
- the new places are intentionally gated for now

**Comment by satanKami** [comment]
yeah i talked to wisteria and when it was the golden knife quest i moved to van and assumed this was the split
-wisteria quest wont trigger the anaha...i forgot the name (just about to sleep)quest
i talked to erant didnt got the letter ...stole from him the letter to trigger it to complete snd there is no follow up

**Comment by satanKami** [comment]
off topic: btw can you say in few word or guild to modpacking? i want to make modii's bee quest "bee ready for pain"

**Comment by teagan75** [comment]
Ok so I didn’t complete the Strahd invitation. I must have gotten distracted lol. 

I will check on the other things. 

As far as modpacks, it is way too complicated to say in a few words but this will help http://kehaan.me/?p=376 and this https://clients.mcprohosting.com/knowledgebase/237/How-to-Import-a-Create-A-Modpack-Using-the-Twitch-Desktop-App.html. As far as recipe changes I use Crafttweaker and Minetweaker recipe maker for an in game GUI

**Comment by teagan75** [comment]
The Arthana quest is fine but the broom one wasn’t attached to the dialogue.

**Comment by satanKami** [comment]
thanks for helping me in my off topic question
ive reported all the quest that was a viable to use and ive used new map as always 
so untill next update this was the final report

**Comment by teagan75** [comment]
Keeping this open so I don’t forget to change things. Also figured out the Arthana issue while recording 😁

**Comment by teagan75** [comment]
Keeping this open so I don’t forget to change things. Also figured out the Arthana issue while recording 😁

**Comment by satanKami** [comment]
lol so yay i was right!
off topic: 
and modii's pack is going nicely there i have a storyline modii would like and im going to do vanilla start with the mod so he can understand why people added ad on to the mod and then adding quests for the making that mod easy...

**Comment by teagan75** [comment]
Nice! And yes I even said you were right in my vid 😝

**Comment by satanKami** [comment]
lol then i guess ill wait for that video

**Comment by teagan75** [comment]
most of this should be fixed in 1.6.3
